# Generated by Django 5.2.5 on 2026-01-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_avatar_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
