# Generated by Django 5.2.5 on 2026-02-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_privacy_policy_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='term_and_condition_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
