# Generated by Django 5.2.5 on 2026-06-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_github_userprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='privacy_policy_accepted',
            new_name='privacy_and_terms_accepted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='term_and_condition_accepted',
        ),
    ]
